Updates the code from the latest version in Gist

diff --git a/docker-asciidoctor-builder b/docker-asciidoctor-builder
--- a/docker-asciidoctor-builder
+++ b/docker-asciidoctor-builder
@@ -2,30 +2,66 @@
 set -eou pipefail
 
 BASE_DIR=${BASE_DIR:-$PWD}
-BUILDER_DIR=`cd "$(dirname "$0")"; pwd -P`
+! [[ `uname` = Darwin ]] || {
+    command -v greadlink &> /dev/null || {
+      echo "Install greadlink! ($ brew install coreutils)"
+      exit 1
+    }
+    readlink() { greadlink "${@:-}"; }
+}
+BUILDER_DIR=`dirname "$(readlink -m "$(which "$0")")"`
 
 cd "$BASE_DIR"
-echo "Base dir is \"$PWD\"."
 
-config=build.conf
-defaults=~/.${0##*/}
+config=.${0##*/}
+defaults=~/$config
 source ./$config 2>&- && {
-  echo "File \"$config\" found. Merging it with defaults ($defaults)."
+  echo "File \"$config\" found. Merging it with defaults (~/${defaults##$HOME/})."
 } || {
-  echo "File \"$config\" not found. Using defaults ($defaults)."
+  echo "File \"$config\" not found. Using defaults (~/${defaults##$HOME/})."
 }
-[ -f "$BUILDER_DIR" ] || (cd; ln -sf ${BUILDER_DIR##$HOME/}/$config $defaults)
+[ -f "$BUILDER_DIR" ] || (cd; ln -sf "${BUILDER_DIR##$HOME/}/$config" $defaults)
 source "$defaults"
 
-docker-asciidoctor() {
+echo "Base dir is \"$PWD\"."
+echo "USE_DOCKER is \"$USE_DOCKER\"."
+
+# tag::INTERNAL_FUNCTIONS[]
+
+__docker-asciidoctor() {
+  local installed_docker=$(which docker || echo -n "uninstalled")
   case $1 in
-    asciidoctor) echo "Generating HTML version ...";;
-    asciidoctor-pdf) echo "Generating PDF version ...";;
+    asciidoctor) echo "Generating HTML version ($HTML_NAME) ...";;
+    asciidoctor-pdf) echo "Generating PDF version ($PDF_NAME) ...";;
   esac
-  docker run -e TZ=America/Sao_Paulo -it --rm \
-    -v "$PWD":/documents \
-    asciidoctor/docker-asciidoctor "$@"
+  if [ "$installed_docker" = "uninstalled" ]
+  then
+    echo "WARNING: docker isn't installed! fallback to \"$1\""
+    eval "$@"
+  else
+    if $USE_DOCKER
+    then
+      $installed_docker run -e TZ=America/Sao_Paulo -it --rm \
+        -v "$PWD":/documents \
+        asciidoctor/docker-asciidoctor "$@"
+    else
+      eval "$@"
+    fi
+  fi
+  case "`uname`" in
+    Linux) sudo chown -R $USER: "${BUILD_DIR%%/*}";;
+  esac
 }
+
+__generate-html() {
+  __docker-asciidoctor asciidoctor -D "$BUILD_DIR" ${attrs:-} "$ADOC" -o "$HTML_NAME"
+}
+
+__generate-pdf() {
+  __docker-asciidoctor asciidoctor-pdf -D "$BUILD_DIR" ${attrs:-} "$ADOC" -o "$PDF_NAME"
+}
+
+# end::INTERNAL_FUNCTIONS[]
 
 html() {
   local tag
@@ -56,6 +92,7 @@ html() {
         BUILD_DIR=$BUILD_DIR/$tag
       ;;
       -p) production=true;;
+      -g|--generate-pdf) GENERATE_PDF=true;;
     esac
     shift || break
   done
@@ -66,24 +103,40 @@ html() {
   echo -n "Building $ADOC "
   $production && echo "for production ..." || echo "for development ..."
   if ! $production && ! [ "${attrs:-}" ]; then attrs="-a env-localhost"; fi
-  docker-asciidoctor asciidoctor -D "$BUILD_DIR" ${attrs:-} "$ADOC" -o index.html
-  ! $GENERATE_PDF || docker-asciidoctor asciidoctor-pdf -D "$BUILD_DIR" ${attrs:-} "$ADOC" -o "`basename "$BASE_DIR"`.pdf"
-  ! [ -d outputs ] || rsync -a outputs "$BUILD_DIR"/
+  __generate-html
+  ! $GENERATE_PDF || __generate-pdf
+  ! [ -d images ] || {
+    if [ -L images ]
+    then
+      (cd "$BUILD_DIR"; rm -rf images; ln -s "$OLDPWD"/images)
+    else
+      rsync -a images "$BUILD_DIR"/
+    fi
+  }
   if [ "${tag:-}" ]; then
     git checkout master &> /dev/null
     git stash pop &> /dev/null || :
   fi
 }
 
+# TODO
+pdf() {
+  :
+}
+
 gh-pages() {
   [ -d $BUILD_DIR ] || { echo "\"$BUILD_DIR\" directory does not exists!"; return 1; }
   echo "Publish the contents in \"$BUILD_DIR\" to GitHub Pages ..."
-  local msg="Published at `date`"
+  local msg="Published at `date +"%F %T %z"`"
   cd "$BUILD_DIR"
-  git init
+  if $RESTART_GH_PAGES
+  then
+    rm -rf .git
+    git init
+  fi
   git add -A
   git commit -m "$msg"
-  git push --force $REMOTE_REPO master:gh-pages
+  git push --force $REMOTE_REPO $MAIN_BRANCH:gh-pages
 }
 
 serve() {
@@ -108,6 +161,6 @@ else
 fi
 shift || :
 type $task &> /dev/null || usage
-$task ${@:-}
+$task "${@:-}"
 
 # vim: et ts=2 sw=2
